version: "3.5"
services:
  front-app:
    build: ./front
    image: test-crud-app   
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - my-app
  server-app:
    depends_on:
      - db
    build: ./server
    image: server-crud-app   
    ports: 
      - "4000:4000"
    networks:
      - my-app
    stdin_open: true
    tty: true
  db:
    image:  mongo:3.6.19-xenial
    restart: unless-stopped 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"
    networks:
      - my-app
    volumes:
      - mongo-data:/data/db

networks:
  my-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local